# Generated by Django 3.2.19 on 2023-06-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0002_remove_lab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.SlugField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
