# Generated by Django 3.2.19 on 2023-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0003_lab_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
