# Generated by Django 3.2.18 on 2023-10-24 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 12, 44, 44, 512758, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
