# Generated by Django 3.2.19 on 2023-10-30 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0008_auto_20231024_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 30, 5, 33, 32, 982973, tzinfo=utc)),
        ),
    ]
